
lovebegin: 2017-07-27

banner: /img/banner.jpg

# å·¦è¾¹å¤´åƒçš„åç§°
leftname: boyname
leftavatar: /img/boyavatar.jpg

# å³è¾¹å¤´åƒçš„åç§°
rightname: grilname
rightavatar: /img/girlavatar.jpg


slogan: ğŸ’•æ„¿ä½ ä¸‰å†¬æš–ï¼Œæ„¿ä½ å¤©ä¸å¯’ğŸ‚

# ç«™ç‚¹åç§°
sitename: ğŸ’–é‚£å¹´åˆå¤ğŸ’–

